# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # notify discord
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Compose message
        id: msg
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "content=I have pushed to my public repo! ${GITHUB_REPOSITORY}@${GITHUB_REF_NAME} : ${SHORT_SHA}%0AAuteur : ${GITHUB_ACTOR}%0A${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Send to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CONTENT: ${{ steps.msg.outputs.content }}
        run: |
          curl -sS -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"$CONTENT\"}"
